// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scraper.Infrastructure.DbContexts;

#nullable disable

namespace Scraper.Infrastructure.Migrations
{
    [DbContext(typeof(ScraperWriteDbContext))]
    partial class ScraperWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scraper.Domain.Entities.OrderToScrape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Urls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("urls");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Scraper.Domain.Entities.ScrapingNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorScraping")
                        .HasColumnType("text")
                        .HasColumnName("error_scraping");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<Guid>("OrderToScrapeId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_to_scrape_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_notices");

                    b.HasIndex("OrderToScrapeId")
                        .HasDatabaseName("ix_notices_order_to_scrape_id");

                    b.ToTable("notices", (string)null);
                });

            modelBuilder.Entity("Scraper.Domain.Entities.ScrapingNotice", b =>
                {
                    b.HasOne("Scraper.Domain.Entities.OrderToScrape", null)
                        .WithMany("Notices")
                        .HasForeignKey("OrderToScrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notices_orders_order_to_scrape_id");
                });

            modelBuilder.Entity("Scraper.Domain.Entities.OrderToScrape", b =>
                {
                    b.Navigation("Notices");
                });
#pragma warning restore 612, 618
        }
    }
}
